name: "🚀 Release"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: build and release tarballs
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - name: install & build
        run: npm ci && npm run build
      - name: pack all packages
        run: |
          cd packages/core && npm pack && cd -
          cd packages/fuzzer && npm pack && cd -
          cd packages/bug-detectors && npm pack && cd -
          cd packages/hooking && npm pack && cd -
          cd packages/instrumentor && npm pack && cd -
          cd packages/jest-runner && npm pack && cd -
      - name: create release with tarballs
        uses: softprops/action-gh-release@v2
        with:
          files: packages/**/*.tgz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
